name: drawing_trainer
description: "App supporting hand-drawing."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  camera: ^0.10.5+9
  json_annotation: ^4.8.1
  json_theme: ^6.4.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.11
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  firebase_auth: ^4.19.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
     - assets/
     - .env
  generate: true